const CORPUS = new Map([
  ["a", {abbr:"A.",lang:"Assamese"}],
  ["b", {abbr:"B.",lang:"Bengali"}],
  ["g", {abbr:"G.",lang:"Gujarati"}],
  ["h", {abbr:"H.",lang:"Hindi"}],
  ["kan", {abbr:"Kan.",lang:"Kannada"}],
  ["kash", {abbr:"Kash.",lang:"Kashmiri"}],
  ["kh", {abbr:"Kh.",lang:"Khasi"}],
  ["kon", {abbr:"Kon.",lang:"Konkani"}],
  ["mal", {abbr:"Mal.",lang:"Malayalam"}],
  ["m", {abbr:"M.",lang:"Manipuri"}],
  ["mar", {abbr:"Mar.",lang:"Marathi"}],
  ["n", {abbr:"N.",lang:"Nepali"}],
  ["o", {abbr:"O.",lang:"Oriya"}],
  ["p", {abbr:"P.",lang:"Punjabi"}],
  ["s", {abbr:"S.",lang:"Sanskrit"}],
  ["tam", {abbr:"Tam.",lang:"Tamil"}],
  ["tel", {abbr:"Tel.",lang:"Telugu"}],
  ["u", {abbr:"U.",lang:"Urdu"}],
  ["sci", {abbr:"Sci.",lang:"Scientific name"}],
  ["common", {abbr:"Common",lang:"Common name"}],
]);
module.exports = CORPUS;
